#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
    path: /
    controller: App\Controller\LoginController::index
    methods: [GET]

login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: [POST,GET]
